site_name: openSUSE User Documentation Project
repo_url: https://github.com/Nycticorax/openSUSE-docs-revamped
edit_uri: ""

plugins:
    - search
    - git-revision-date
    - mkdocs-versioning:
        version: 0.3.1
    - pdf-export:
        verbose: true
        media_type: print
        #enable PDF printing by running "export ENABLE_PDF_EXPORT=1"
        enabled_if_env: ENABLE_PDF_EXPORT
        #comment out the next two options to make every page have its own PDF
        combined: true
        combined_output_path: docs.pdf

site_favicon: https://static.opensuse.org/favicon.svg

theme:
    name: mkdocs
    custom_dir: 'theme/'
    nav_style: custom sticky-top mb-3

extra_javascript:
- js/extra.js
- https://static.opensuse.org/chameleon-3.0/dist/js/chameleon.js

copyright: © 2020–2021 openSUSE contributors


footer_links:
  - text: Source Code
    link: https://github.com/openSUSE/openSUSE-docs-revamped
# Remove that comment when the license is there ;)
#  - text: License
#    link: https://github.com/openSUSE/openSUSE-docs-revamped/blob/master/LICENSE

markdown_extensions:
    - admonition
    - def_list
    - pymdownx.details
    - pymdownx.superfences
    - toc:
        permalink: ⚓︎
        toc_depth: 5

nav:
    - Home: index.md
    - Version Selector: "../"
    - Before installing:
        - Choosing the right image: pick_an_image.md
        - Installation setups: ""
        - Preparing the installation media: media_choice.md
    - Installing:
        - Step by step guide: 
            - openSUSE Leap: leap_installer.md
            - openSUSE Tumbleweed: tw_installer.md
        - Quick install for experienced users:
            - microOS specials: microos_getting_started.md
    - Distro basics:
        - KDE Plasma basics: ""
        - GNOME basics: ""
        - Interlude -- Fundamental openSUSE concepts:
            - Snapper: snapper.md
        - Getting & installing software: ""
        - Updating and upgrading: ""
        - Managing snapshots: ""
        - Troubleshooting with autonomy: ""
    - Completing and fine-tuning your setup:
        - Finding & installing additional software:
            - NVIDIA driver: install_proprietary.md 
        - Security basics: ""
        - Wifi & network: ""
        - Power management: ""
        - Pairing, syncing, sharing:
            - Bluetooth: bluetooth.md
        - Advanced fine-tunings: ""
        - More partitioning: ""
        - Recommended setups: ""
    - Giving back to the community:
        - Reporting bug reports: ""
        - Resources: ""
        - Other sources of documentation: reference_docs.md
        - Contribute to this docs: 
            - Markdown flavour: markdown.md
            - Todo: todo.md
    - A contributor's checklist:
        - openSUSE distributions: ""
        - desktop Environments: ""
        - getting the right installer: ""
        - FAQ, Issues & solutions: ""
